[package]
name = "warlot"
edition = "2024"

[dependencies]
wal    = { git = "https://github.com/MystenLabs/walrus.git", subdir = "testnet-contracts/wal",    rev = "0d671d3cd27d18df6b6edb6e3efcf44e4fffcbdc" }
walrus = { git = "https://github.com/MystenLabs/walrus.git", subdir = "testnet-contracts/walrus", rev = "0d671d3cd27d18df6b6edb6e3efcf44e4fffcbdc" }
